services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: container-registry.oracle.com/database/free:latest
    environment:
      ORACLE_PWD: oracle
      ORACLE_SID: FREE
      ORACLE_CHARACTERSET: AL32UTF8
    ports:
      - "1521:1521"
    networks:
      - app-network
    volumes:
    - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "echo 'SELECT 1 FROM dual;' | sqlplus -s sys/oracle@FREE as sysdba" ]
      interval: 10s
      timeout: 5s
      retries: 20

networks:
  app-network:
    driver: bridge
